# -*- coding: utf-8 -*-
# These are the required packages need for this python file to run completely
import scrapy
from datetime import datetime

# References the items file which is where the user specifies the items that need to be scraped
from ..items import PracticumItem

# We need to define a start url or the website we are interested in scraping
urls = 'https://blogs.cdc.gov/'


# Defining the class statement to be executed. This contains the whole scraping process
class CDCSpider(scrapy.Spider):
    # name = declaring the name of spider for later use in program
    name = 'cdc'

    # This first function starts the request by loading the provided url above.
    # This function will then call the parse_cover function.
    def start_requests(self):
        yield scrapy.Request(url=urls,
                             callback=self.parse_cover)

    # First parsing method. Scrapes the first Web page generated by the start_requests function.
    # The CDC url has multiple blog websites so we need to go into each blog website separately
    def parse_cover(self,response):
        # blog links are the scraped links to each blog website found in the HTML of the URL
        blog_links = response.xpath('//ul/li/a/@href')
        # extracts the links from the scraped blog_links
        blogs_to_follow = blog_links.extract()

        # This for loop will loop through the extracted blog links and for each blog website,
        # call the parse_front function.
        for blogs in blogs_to_follow:
            yield response.follow(url=blogs,
                                  callback=self.parse_front)

    # Second parsing method. Scrapes the first Web page generated by the parse_cover function.
    def parse_front(self, response):
        # next_page will use the specified locator to grab the url for the next page
        next_page = response.xpath('//div[@class = "next"]//a/@href').extract()

        # article_links are the urls corresponding to each blog post. These need to be collected
        # to "go into" the blog post.
        article_links = response.xpath('//div[@class = "cdc-listing-post "]/h3/a/@href')
        # extracts the links from the scraped article_links
        links_to_follow = article_links.extract()

        # This for loop will loop through the extracted blog links and for each blog,
        # call the parse_pages function.
        for link in links_to_follow:
            yield response.follow(url=link,
                                  callback=self.parse_pages)

        # This if statement will execute if the nest_page locator got a response from the HTML.
        # If there was a next_page value, then it will go to that url and call parse_front again.
        if next_page is not None:
            yield response.follow(next_page, callback=self.parse_front)

    # the parse_pages function collects the information from the individual blog posts.
    def parse_pages(self, response):

        # calls the items.py file. The items file specifies which data points are being collected
        items = PracticumItem()

        # These are the locators for this particular blog website. These locators can be found
        # in the HTML text of the website. these locators are specific for this website
        twitter = []
        article_date = response.xpath('//time[@class = "entry-date published updated"]/text()').extract()
        article_title = response.xpath('//h1/text()').extract()
        author = response.xpath('//span[@class = "cdc-author"]/text()').extract()
        article_text = response.xpath('//div[@class = "syndicate"]//p/text()').extract()


        body = ''
        for text in article_text:
            body = body + text
        # These 3 lines clean up the body by removing new lines, tabs, and carriage return
        body = body.replace('\r', '')
        body = body.replace('\n', '')
        body = body.replace('\t', '')

        # Error handling if certain extracts do not catch anything. his way we insert a blank string
        # so we can still insert the record into the database
        if len(twitter) > 0:
            items['twitter'] = twitter[0]
        else:
            items['twitter'] = ''
        if len(article_date) > 0:
            items['article_date'] = article_date[0]
        else:
            items['article_date'] = ''
        if len(author) > 0:
            items['author'] = author[0]
        else:
            items['author'] = ''
        if len(article_title) > 0:
            items['article_title'] = article_title[0]
        else:
            items['article_title'] = ''
        items['article_url'] = response.request.url
        items['article_text'] = body
        items['timestamp'] = datetime.now()

        # The yield items will yield the extracted items and put through the pipeline.
        # The pipeline was specified in the settings file by uncommenting the code below:
        # ITEM_PIPELINES = {
        #     'practicum.pipelines.PracticumPipeline': 300,
        # }
        yield items
