# -*- coding: utf-8 -*-
# These are the required packages need for this python file to run completely
import scrapy
from datetime import datetime

# References the items file which is where the user specifies the items that need to be scraped
from ..items import PracticumItem

# We need to define a start url or the website we are interested in scraping
urls = 'https://www.npr.org/sections/health-shots/'


# Defining the class statement to be executed. This contains the whole scraping process
class NprSpider(scrapy.Spider):
    # name = declaring the name of spider for later use in program
    name = 'Npr'

    # start_blog will be the counter for our loop. his will allow the spider to loop
    # through multiple blogs
    start_blog = 1

    # This first function starts the request by loading the provided url above
    def start_requests(self):
        yield scrapy.Request(url=urls,
                             callback=self.pages)

    # This function will load the first set of blogs by using the counter(year)
    # This function will then call parse_front to collect the blog links.
    def pages(self,response):

        # start_url starts at the first blog which is referenced by the counter(start_blog)
        start_url = 'https://www.npr.org/get/103537970/render/partial/next?start=' + str(NprSpider.start_blog)
        yield response.follow(start_url, callback=self.parse_front)

    # Second parsing method. Scrapes the first Web page generated by the start_requests function.
    def parse_front(self, response):

        # article_links are the urls corresponding to each blog post. These need to be collected
        # to "go into" the blog post.
        article_links = response.xpath('//h2[@class = "title"]/a/@href')

        # extracts the links from the scraped article_links
        links_to_follow = article_links.extract()

        # This will loop through each link in the list of blog links. The response will "click"
        # on each blog to go into the blog post. Every time a blog post is "clicked" on, it will add
        # 1 to the counter. Then the function will then call the parse_pages function
        for link in links_to_follow:
            NprSpider.start_blog += 1
            yield response.follow(url=link,
                                  callback=self.parse_pages)

        # This if statement says that if the program has found any links on the previously scraped website,
        # it will go into this next_page statement which is the next page of the website. If there were no
        # links found on the previous page. The program will stop scraping as there were no more blogs to be scraped.
        if links_to_follow != [] :
            next_page = 'https://www.npr.org/get/103537970/render/partial/next?start=' + str(NprSpider.start_blog)
            yield response.follow(next_page, callback=self.parse_front)

    # the parse_pages function collects the information from the individual blog posts.
    def parse_pages(self, response):

        # calls the items.py file. The items file specifies which data points are being collected
        items = PracticumItem()

        # These are the locators for this particular blog website. These locators can be found
        # in the HTML text of the website. these locators are specific for this website
        article_date = response.xpath('//span[@class = "date"]//text()').re(r"\w+\s\d{1,2},\s\d{4}")
        article_title = response.xpath('//div[@class = "storytitle"]//h1//text()').extract()
        author = response.xpath('//p[@class = "byline__name byline__name--block"]/a/text()').re(r"[A-Z]\w+\s\w+")
        article_text = response.xpath('//p//text()').extract()
        twitter = []

        # The article text is sometimes in separate paragraphs so this "body" function
        # will combine the paragraphs into one
        body = ''
        for text in article_text:
            body = body + text
        # These 3 lines clean up the body by removing new lines, tabs, and carriage return
        body = body.replace('\r', '')
        body = body.replace('\n', '')
        body = body.replace('\t', '')

        # Error handling if certain extracts do not catch anything. his way we insert a blank string
        # so we can still insert the record into the database
        if len(twitter) > 0:
            items['twitter'] = twitter[0]
        else:
            items['twitter'] = ''
        if len(article_date) > 0:
            items['article_date'] = article_date[0]
        else:
            items['article_date'] = ''
        if len(article_title) > 0:
            items['article_title'] = article_title[0]
        else:
            items['article_title'] = ''
        if len(author) > 0:
            items['author'] = author[0]
        else:
            items['author'] = ''
        items['article_url'] = response.request.url
        items['article_text'] = body
        items['timestamp'] = datetime.now()

        # The yield items will yield the extracted items and put through the pipeline.
        # The pipeline was specified in the settings file by uncommenting the code below:
        # ITEM_PIPELINES = {
        #     'practicum.pipelines.PracticumPipeline': 300,
        # }
        yield items

