# -*- coding: utf-8 -*-
# These are the required packages need for this python file to run completely
import scrapy
from datetime import datetime

# References the items file which is where the user specifies the items that need to be scraped
from ..items import PracticumItem

# We need to define a start url or the website we are interested in scraping
urls = 'http://thehill.com/blogs/healthwatch'


# Defining the class statement to be executed. This contains the whole scraping process
class TheHillSpider(scrapy.Spider):
    # name = declaring the name of spider for later use in program
    name = 'thehill'

    # This first function starts the request by loading the provided url above.
    # This function will then call the parse_front function.
    def start_requests(self):
        yield scrapy.Request(url=urls,
                             callback=self.parse_front)

    # First parsing method. Scrapes the first Web page generated by the start_requests function.
    def parse_front(self, response):
        # next_page will use the specified locator to grab the url for the next page
        next_page = response.xpath('//li[@class="pager-next last"]/a/@href').get()

        # article_links are the urls corresponding to each blog post. These need to be collected
        # to "go into" the blog post.
        article_links = response.xpath('//h2[@class="node__title node-title"]/a/@href')
        # extracts the links from the scraped article_links
        links_to_follow = article_links.extract()

        # This for loop will loop through the extracted blog links and for each blog,
        # call the parse_pages function.
        for link in links_to_follow:
            yield response.follow(url=link,
                                  callback=self.parse_pages)

        # This if statement will execute if the nest_page locator got a response from the HTML.
        # If there was a next_page value, then it will go to that url and call parse_front again.
        if next_page is not None:
            yield response.follow(next_page, callback=self.parse_front)

    # the parse_pages function collects the information from the individual blog posts.
    def parse_pages(self, response):

        # calls the items.py file. The items file specifies which data points are being collected
        items = PracticumItem()

        # These are the locators for this particular blog website. These locators can be found
        # in the HTML text of the website. these locators are specific for this website
        twitter = []
        article_date = response.xpath('//span[(@class="submitted-date")]//text()').extract()
        article_title = response.xpath('//h1[(@id = "page-title")]//text()').extract()
        author = response.xpath('//*[@id="main"]/div[3]/div[2]/div/span/a//text()').extract()
        article_text = response.xpath('//div[@class="field-items"]//p//text()').extract()

        # The article text is sometimes in separate paragraphs so this "body" function
        # will combine the paragraphs into one
        body = ''
        for text in article_text:
            body = body + text
        # These 3 lines clean up the body by removing new lines, tabs, and carriage return
        body = body.replace('\r', '')
        body = body.replace('\n', '')
        body = body.replace('\t', '')

        # Error handling if certain extracts do not catch anything. his way we insert a blank string
        # so we can still insert the record into the database
        if len(twitter) > 0:
            items['twitter'] = twitter[0]
        else:
            items['twitter'] = ''
        if len(author) > 0:
            items['author'] = author[0]
        else:
            two_authors = response.xpath('//span[@class = "submitted-by"]//text()').extract()
            items['author'] = two_authors[0]
        if len(article_date) > 0:
            items['article_date'] = article_date[0]
        else:
            items['article_date'] = ''
        if len(article_title) > 0:
            items['article_title'] = article_title[0]
        else:
            items['article_title'] = ''
        items['article_url'] = response.request.url
        items['article_text'] = body
        items['timestamp'] = datetime.now()

        # The yield items will yield the extracted items and put through the pipeline.
        # The pipeline was specified in the settings file by uncommenting the code below:
        # ITEM_PIPELINES = {
        #     'practicum.pipelines.PracticumPipeline': 300,
        # }
        yield items

